config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "home#index"

  namespace :admin do
    resources :products
    resources :categories
  end

  resources :analytics, only: [:index]

  resources :brand, only: [:index]
  resources :carts, only: [:index, :show, :edit, :update, :destroy]
  resources :checkout, only: [:create]

  resources :products, only: [:index, :show]
  resources :product_categories, only: [:index, :show]
  resources :product_subscriptions, only: [:create, :show]
  resources :search, only: [:index]
  resources :reviews, only: [:show, :create]
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>SkateShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">
  <script src="https://js.stripe.com/v3/"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.4.1/purify.min.js"></script>
  </head>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <img width="75" src="<%= asset_path('SkullysSkateShop_Exploration-08.png') %>">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="d-flex navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Products", products_path, class: "nav-link"%>
                </li>
                <% ProductCategory.all.each do |category| %>
                <li>
                    <%= link_to category.name, category, class: "nav-link" %>
                </li>
                <% end %>
                <li class="nav-item"><%= link_to "The Brand", brand_index_path, class: "nav-link" %></li>
            </ul>

            <%= form_with url: search_index_path, method: :get do |form| %>
                <%= form.text_field :keyword, class: "form-control me-2" %>
                <%= form.submit "Search", class: "btn btn-outline-success" %>
            <% end %>

            <div class="d-flex">
            <% if user_signed_in? %>
                <span class="align-middle">
                    Welcome <%= current_user.email %>
                </span>

                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
            <% else %>
                <%= link_to "Login",
                new_user_session_path, class: "btn btn-secondary" %>
            <% end %>
            </div>
            <div class="d-flex">
                <%= link_to "Cart: #{number_to_currency(cart_for_user.total)}", "/carts/#{cart_for_user.id}", class: "nav-link" %>
            </div>
        </div>
    </div>
</nav>

<body>
    <div class="container">
        <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.js"></script>
</body>
</html>